build-GetCardsFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-GetCardByIdFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-GetSetsFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-GetCollectionFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-AddToCollectionFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-GetCollectionEntryFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-UpdateCollectionEntryFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-RemoveFromCollectionFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-GetCompletionSummaryFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build

build-HealthCheckFunction:
	cd $(ARTIFACTS_DIR) && npm install && npm run build
